name: gnss_rep
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - obspy
  - scikit-learn
  - pyproj
  - pandas
  - jupyterlab
  - ipympl
  - pytest
  - tqdm
  - h5py
  - colorcet
  - lxml
  - rich
  - pip
  - pip:
    - pysindy

